profiles:
  - name: "松下恵（まつめぐ）"
    title: "潜在意識クリエーター"
    description: "本気フェスクルーでもご一緒し、北原さんの顧問契約、今は株北メンバーと並んでご活躍中🌟<br>
6人のママながらも年商８桁の愛溢れでる潜在意識クリエイターです✨✨"
    photo: "https://prd.storage.lit.link/images/creator/vHJq3VatwuT40kUs016RVl4ixPM2/96622bf8-f2ba-4c02-b68d-96e6a2508591.png"
    links:
      - type: litlink
        url: "https://lit.link/megu0726"
      - type: instagram
        url: "https://www.instagram.com/matumegu726"
  - name: "今岡勇喜"
    title: ""
    description: "成約導線設計コンサル"
    photo: "https://i.gyazo.com/17a57ea9ace3a48bc1252bb576d4b79a.jpg"
    links:
      - type: instagram
        url: "https://www.instagram.com/imaoka____yuuki/"
  - name: "白鳥ねね"
    title: "職業 Princess"
    description: ""
    photo: "https://i.gyazo.com/21a5a37de5549d1b4d4c040bf428b4d6.png"
    links:
      - type: instagram
        url: "https://www.instagram.com/balletriena/"
  - name: "湯滝翔"
    title: "夢叶　星詠みヒーラー"
    description: ""
    photo: "https://gyazo.com/ac58b6525fdfb169bd4393e642b04a74.jpg"
    links:
      - type: instagram
        url: "https://www.instagram.com/sho_honki/"
  - name: "吉田収"
    title: "半年で-35kg"
    description: ""
    photo: "https://i.gyazo.com/da1440d54d28fa52dda7f9b3663347fd.png"
    links:
      - type: instagram
        url: "https://www.instagram.com/yoshida_40kgdiet/"
  - name: "内田琴美"
    title: "salon de create主宰"
    description: ""
    photo: "https://i.gyazo.com/9d4e81eeb76b07c8cb91c09f32a4ca18.jpg"
    links:
      - type: instagram
        url: "https://www.instagram.com/kotomi.uchida/"
  - name: "佐藤あすか"
    title: "起業ライフデザインコーチ"
    description: ""
    photo: "https://i.gyazo.com/dec3318d20ec326cd16ccc03e2d44826.png"
    links:
      - type: instagram
        url: "https://instagram.com/asuka_coach"
  - name: "ゆーちゃん（高橋雄太）"
    title: "エンジニア恋愛コンサルタント"
    description: "実践式恋愛コンサルでパートナー作りしませんか？｜自分に自信を持つお手伝い｜コミュ障エンジニアからの笑顔の絶えない結婚生活"
    photo: "https://i.gyazo.com/8b7f16f777069dcdcd1759e2975aa646.jpg"
    links:
      - type: instagram
        url: "https://www.instagram.com/yuchan_314/"
      - type: twitter
        url: "https://twitter.com/tashua314"
  - name: "荻原空"
    title: "集客・採用に特化したTikTok運用代行"
    description: ""
    photo: "https://i.gyazo.com/1bb548296708266492364fc082b2c512.jpg"
    links:
      - type: tiktok
        url: "https://www.tiktok.com/@sora06121?_t=8bgAnWZfLtp&_r=1"
  - name: "中井翔太"
    title: "中小企業のためのシステム会社"
    description: ""
    photo: "https://i.gyazo.com/4ed0ce53b230b05443d5ffa15b2bd3f4.jpg"
    links:
      - type: instagram
        url: "https://www.instagram.com/sho_mdniz/"
  - name: "金城さやか"
    title: "集客コンサルタント"
    description: ""
    photo: "https://i.gyazo.com/994efc8c7e299c22edefda104d5050c6.png"
    links:
      - type: instagram
        url: "https://www.instagram.com/kinjo.saya"
  - name: "宮本佳浩"
    title: "治療家"
    description: ""
    photo: "https://i.gyazo.com/02cf12fddd653655a1f65bc0a3ed1ae0.jpg"
    links:
      - type: instagram
        url: "https://instagram.com/yoshihiro_m1110?igshid=YmMyMTA2M2Y="
  - name: "髙橋学(まなぶん)"
    title: "アニバーサリーソングライター"
    description: ""
    photo: "https://i.gyazo.com/58eeaacd462d24498c21ed6038039aaf.jpg"
    links:
      - type: instagram
        url: "https://www.instagram.com/mana_buuuuun/"
  - name: "TATSUKI"
    title: "SNS総フォロワー数 1万人食農社長"
    description: ""
    photo: "https://i.gyazo.com/b6b31077a04156373b65a539c448e80d.jpg"
    links:
      - type: instagram
        url: "https://www.instagram.com/tatsuki_nogyo/"
  - name: "羽田宗一郎"
    title: "株式会社キッカケ　ママファースト代表"
    description: ""
    photo: "https://i.gyazo.com/211ce7732a41dca3caf195463f520123.jpg"
    links:
      - type: instagram
        url: "https://instagram.com/company_kikkake?igshid=YmMyMTA2M2Y="
  - name: "中賀巧"
    title: "講演会 / プロデューサー"
    description: ""
    photo: "https://i.gyazo.com/a18326a80985f2dc7c5168c2cfb510e3.jpg"
    links:
      - type: instagram
        url: "https://instagram.com/takumi_enmusubiya?igshid=YmMyMTA2M2Y="
  - name: "小宅　春樹"
    title: "一般社団法人　日本オアシス　代表理事"
    description: ""
    photo: "https://i.gyazo.com/af3b757ecd2164e49757576f391c06a8.jpg"
    links:
      - type: instagram
        url: "https://instagram.com/haruki_oyake?igshid=YmMyMTA2M2Y="
