version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - '88:80'
      - '444:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./TechGuide:/usr/share/nginx/html

