name: Build Static Site on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # リポジトリをチェックアウト
        with:
          ref: main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name:  S3 sync
        working-directory: design/TechGuide
        run: aws s3 sync . s3://techguide.jp --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --include "design/TechGuide/*"
      - name:  S3 sync events
        working-directory: events
        run: aws s3 sync . s3://techguide.jp/redirects --delete --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --include "events/*"
